export {default as Navbar} from './navbar/Navbar'
export {default as Hero} from './hero/Hero'
export {default as Team} from './team/Team'
export {default as Vision} from './vision/Vision'
export {default as CTA} from './cta/CTA'
export {default as Footer} from './footer/Footer'